name: Merge CSV Files

on:
  push:
    branches: [ main ]

jobs:
  merge-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/xmp3/settings.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run CSV merge script
        run: |
          python merger.py dataframes ../settings/tracks.csv

      - name: Commit and push changes
        run: |
          cd settings
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tracks.csv
          git commit -m "Update tracks.csv"
          git push origin main
